### ISSUE TITLE
Merge the code to home assistant

### ISSUE THREAD

**Issue by bogdanr** [jaruba/ha-samsungtv-tizen#131]
How about merging all these changes to home assistant?
It would be more user-friendly to everybody to have the integration available out of the box.

**Comment by jaruba** [comment]
Salut, this has obviously been discussed many times before. We are currently in the process of merging the 2 most popular Samsung TV components into this one. (the second being a fork of this component that has also gotten fame on it's own)

Moving this component to HA's official components is an extremely complicated task that will also require a lot of time invested.

This is because:
- HA's official components have the obligation of moving all internal libraries published separately as modules on PyPi
- HA already has a Samsung TV component which although very limited supports non-smart Samsung TVs as well (this component only supports Smart Samsung TVs)
- when / if it does get accepted as the official component for Samsung TVs, PRs get stuck for months on HA's official components because they need to be approved by HA's staff also, even if they never worked on the component, and being the creator of the component still makes it hard and very long task to make any change to the code

I am not against it become the official component after it has fully matured and ideas for changes / improvements have become minimal, but this is not the case for now. And with a 3 person team working on it today, having to wait months for a change to be accepted will simply demoralize all active developers from continuing to work on it.
