### ISSUE TITLE
samsung-tv-ws-api

### ISSUE THREAD

**Issue by tulindo** [jaruba/ha-samsungtv-tizen#15]
Hello. do you plan to merge your work into https://github.com/xchwarze/samsung-tv-ws-api ?

I'm asking this because it would be nice to have your code used in official HA component. HA policies regarding external libraries requires that they are hosted on pypi... @schwarze's project is.

Btw... great work.

**Comment by jaruba** [comment]
I've tried in the past to make a PR to one of his repos:
https://github.com/xchwarze/ha-samsungtv-custom/pull/2

He doesn't seem to ever respond to any PRs though.

**Comment by tulindo** [comment]
I'm doing some research to understand the state of the art of samtung TV support (I'd like to have the HA official component support samsungtv as their best). 
Samsungctl (the kdschlosser version) has a lot of features (and supports also legacy TV). Is your samsungtvws supporting additional TVs? 
What are additional features added by your api? 
Thanks

**Comment by jaruba** [comment]
I have been summoned!
![source](https://user-images.githubusercontent.com/1777923/73501078-3c76d980-43cd-11ea-88c4-e36ab3971cb3.gif)

**Comment by jaruba** [comment]
Mine (and xchwarze's) components are only meant for newer Samsung TVs.

This component was born due to complete lack of interest from the developers of the other components. It merges all the PRs that I considered useful from all the Samsung TVs components I could find. (PRs that were completely ignored in their original repos)

I'm not, by any means, a python developer. I am although a professional developer, mostly working with Node.js these days. And due to the many years of development, I can code in pretty much any language, regardless of experience with the programming language.

With all this said, I consider that when it comes to supporting newer Samsung TVs.. Newer is the important part here, as I don't give a flying fuck about supporting all Samsung TVs, as of 2006 (14 years ago!!) and later all Samsung TVs are radically different, and supporting all Samsung TVs will just cause confusion and bloat the component. I think this happened to roberodin's component, which works very badly for my 2 Samsung TVs (one made in 2006 and one from 2019).

And still, I know for a fact the many limitations of this component, and it's (from what I gather) impossible to gain all features as the APIs themselves are mostly hidden by Samsung and also very limited.

If what you're looking for is a component that handles all possible features of a Samsung TV, then you're looking in the wrong place.

I've investigated this A LOT, I've also used very advanced google jitsu with no success.. My conclusion is that if you want all the features you can have (and more), the solution is the SmartThings Cloud API. Which will support truly amazing features that no other (local) component could ever had.

So that's what I'm planning to do when I'll ever have time (as I have a lot of hobby programming projects...). A Samsung TV component based on the SmartThings Cloud API, that will (finally) support Samsung TVs in all their glory. And no, it won't work at all with older Samsung TVs. (that were created more then 14 years ago!!!!)

**Comment by tulindo** [comment]
I'm not looking for a library to rule them all... my original idea was to use samsungctl for legacy tv and samsungtvws for websocket. As I said on my first post... only problem with your library is that it's not on pypi (and this is a requirement for the official HA version).
I do agree,... main problem is the lack of information about samsung api.

**Comment by jaruba** [comment]
> my original idea was to use samsungctl for legacy tv and samsungtvws for websocket.

@tulindo Have you looked at roberodin's component? It looks to me like it's already doing exactly that. It actually uses `samsungctl_080b`, `samsungctl_qled` and `samsungtvws`. See here:
https://github.com/roberodin/ha-samsungtv-custom/tree/master/custom_components/samsungtv_custom

I'm not a fan of what's going on in his repo tbh, "skeleton key" projects like that can lead to complex documentation and oversimplified logic.

I can try to publish it on pypi if that's what you need, even make PR to `xchwarze/samsungtvws`. (although I don't think he'll respond to it) This would require me to find the necessary time for it though..

**Comment by jaruba** [comment]
I don't believe this is valid anymore. Given the discussions with xchwarze in the other tickets, he states that he does not want to include UPnP solutions in `samsung-tv-ws-api`, as many changes used in this component include such solutions, he would not accept a PR anyway.
