### ISSUE TITLE
State always on

### ISSUE THREAD

**Issue by andreamastro** [jaruba/ha-samsungtv-tizen#25]
I have a problem with media_player entity. Its state is always on. I have tried to set update_method to ping but i have the same problem

**Comment by jaruba** [comment]
There is a bug in the current release, I know about it but have been away from home for a while.

I'll fix it soonish.

**Comment by MacPolak** [comment]
I got “unknown” and this in logs:
`
Wed Feb 26 2020 23:19:46 GMT+0100 (CET)

Update for media_player.samsung_tv_remote fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 260, in update
    smartthings.device_update(self)
  File "/config/custom_components/samsungtv_tizen/smartthings.py", line 37, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) `

**Comment by jaruba** [comment]
@MacPolak you set a wrong smartthings api key or smartthings device id.

generate a new api key and ensure that the device id is correct

**Comment by jaruba** [comment]
The state issue (with the TV remaining in On state) should be fixed in the latest release.

**Comment by andreamastro** [comment]
The problem is still present

**Comment by jaruba** [comment]
@andreamastro that shouldn't be possible, show me your config

**Comment by andreamastro** [comment]
- platform: samsungtv_tizen
   host: 192.168.1.122
   port: 8002
   mac: 54:BD:79:D7:D2:44
   api_key: !secret samsung_api_key
   device_id: !secret samsung_device_id
   source_list: '{"TV": "KEY_SOURCE+50+KEY_LEFT+50+KEY_ENTER", "HDMI": "KEY_SOURCE+50+KEY_LEFT+50+KEY_RIGHT+50+KEY_ENTER"}'
   app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684", "Plex": "3201512006963", "Prime Video": "3201512006785"}'

**Comment by jaruba** [comment]
I see u enabled SmartThings, so why not use ST_TV, ST_HDMI1, ST_HDMI2, ST_HDMI3, etc. in the `source_list`?

Are u absolutely sure u updated this component to the latest version? Because the state issue IS fixed. If u are absolutely sure then u can also try `update_method: "websockets"`. This update method should normally not be as good as the default "ping" method (that should change the TV state correctly in about 10 seconds or so), but who knows, maybe ur TV is some special case.

**Comment by andreamastro** [comment]
Now i use ST_TV, ST_HDMI1, thanks for the advice. I noticed that with ping update method state is always on and with websocket update method state remains on when i turn off tv from media player. It seems work when i turn off tv from remote controller

**Comment by jaruba** [comment]
@andreamastro Absolutely none of the update methods will make it show as off instantly. This is because the TV is NOT OFF, it has a time of about 30-60 seconds when the TV waits for you (with only the screen turned off) to turn it back on in case you turned it off by mistake. This is what Samsung does with all their TVs, I imagine it's for cases when you butt press the remote and want the TV to start again instantly so you don't miss your favorite show.

But this issue is not for "tv not turning off instantly", it's for "state always on", so let's please talk about if the TV stays "On" forever, not if the TV stays "On" for longer then you think it should.

**Comment by andreamastro** [comment]
Yes, i'm talking about "state always on" even after a long time. Anyway i have just update from 1.4.1 to 1.4.2 and the problem seems fixed. Thanks

**Comment by jaruba** [comment]
Uhm, then it might of just been a case of the component not authenticating to the TV correctly.
