### ISSUE TITLE
Home Assistant full unresponsive a soon as v1.4.3 installed and used

### ISSUE THREAD

**Issue by sanderlv** [jaruba/ha-samsungtv-tizen#33]
As soon as version v1.4.3 via HACS is installed and configured in configuration.yaml my entire home assistant is unresponsive. As soon as I delete the config and uninstall via hacs it comes back to normal.

If installed and configured I see the CPU of HA (via Glances) going to almost 100% (always 89.1%) where user cpu is 78.8 and  system 10.2.

something is definitely VERY WRONG here

If configured in the first few minutes it works well and even the TV responds to some commands, but they take very long time to "reach" the TV.

My config:
media_player:
  - platform: samsungtv_tizen
    host: 192.168.1.x
    port: 8002
    mac: xxx

i see these errors in logging:
2020-03-08 14:03:28 ERROR (MainThread) [custom_components.samsungtv_tizen.media_player] Unsupported media type

**Comment by jaruba** [comment]
This doesn't make much sense, did any previous version work better?

The only way a simple component such as this can freeze HA and increase CPU so much is if it goes in an infinite loop, and I don't see how that could happen, but it wouldn't be the first time I would be surprised.

You should try setting the `app_list` value, it may be what's causing ur issues.

**Comment by sanderlv** [comment]
How to set that app_list and why could it cause an issue?

**Comment by jaruba** [comment]
> how to set that app_list

Read the docs: https://github.com/jaruba/ha-samsungtv-tizen/blob/master/README.md

> why could it cause an issue?

Because if u don't set it, it tries to get the app_list from the TV. The only way an infinite loop can happen is within repeating logic. There is a `for` loop that iterates the app_list, so maybe that fails somehow. It's a far fetched scenario, but I can't think of a different scenario yet.

**Comment by sanderlv** [comment]
As soon as I install via HACS the pugin, HA is slower and unresponsive after a while with high user cpu load. First I thought is was due to update to hassos 3.12 but that seems unrelated. I always had some issue with a slow starting system and lots of errors, but as soon as I uninstall this addon all that is gone!? (-sorry-)

I also added the list to try, no difference:
![image](https://user-images.githubusercontent.com/16528916/76193046-7795d500-61e3-11ea-9ed1-fb09a60b3372.png)

Only uncommenting the configuration.yaml does not help, only full uninstall via hacs does.

Some info:
![image](https://user-images.githubusercontent.com/16528916/76193070-82506a00-61e3-11ea-81fa-ac1884680b7d.png)

![image](https://user-images.githubusercontent.com/16528916/76193079-867c8780-61e3-11ea-8d7a-e2082560137b.png)

![image](https://user-images.githubusercontent.com/16528916/76193088-8a100e80-61e3-11ea-9874-a806fc583d5f.png)

Happy to provide more info.

**Comment by jaruba** [comment]
From what you're saying, this component simply cannot be at fault for your issues. And I'll tell you why.

> Only uncommenting the configuration.yaml does not help, only full uninstall via hacs does.

If you don't set a config for the component, the code of the component is not ran AT ALL, and if you add 2 configs (for 2 TVs) then this component WILL RUN TWICE. So if you still have issues when you remove the config, then it simply cannot be because of this component.

The warnings you posted are absolutely normal, you will get those warning for ANY component installed from HACS (or manually).

Furthermore, there are many many users that use this component, and you're the only one with CPU load issues and HA getting slow / frozen.

If you want my opinion, then your issues are either from:
- a bad HA setup (can be anything from bad hardware, what you installed in HA or even HA itself)
- human error (you are misreading data and making wrong presumptions)

Whatever the case may be, at this point (after analysing everything you said) I am certain that this component cannot be at fault. As my responsibilities are to this component and nothing more, I cannot help you find the reason this is happening to you, as it's not this component that's causing issues for you.
