### ISSUE TITLE
Entity Picture support

### ISSUE THREAD

**Issue by zappasmart** [jaruba/ha-samsungtv-tizen#45]
It would be awesome if it was possibile to support the **entity_picture** attribute on the media_player entity, so the media control card could display a picture of what currently is on the TV, like:

- logo of the tv channel
![image](https://user-images.githubusercontent.com/53600373/77628040-0a56a380-6f48-11ea-9825-cffab4666deb.png)
- logo of the active app
![image](https://user-images.githubusercontent.com/53600373/77626900-51439980-6f46-11ea-82b6-07f1d2aec637.png)

**Comment by jaruba** [comment]
Well that sure looks nice, but where are we supposed to get the images for any tv channel (tv channels are also country specific) and/or any tv app?

**Comment by zappasmart** [comment]
Well, this should be part of some technical analysis :)

**Comment by jaruba** [comment]
sounds more like grunt work then technical analysis tbh.. unless more from the community favour this and start offering to help with it (including yourself), it may be too much of a burden for one person to research / implement

**Comment by jaruba** [comment]
I've been thinking more about this, and I do believe it's possible to make such a feature with the use of the TMDB API.

The docs for the daily db exports (of tv networks):
https://developers.themoviedb.org/3/getting-started/daily-file-exports

Example of contents from an export:
```
{"id":1062,"name":"HBO Nordic"}
{"id":1063,"name":"Sky Atlantic"}
{"id":1064,"name":"RMC Découverte"}
```

This will give us the list of all TV networks on TMDB, but only their IDs and names. The export for TV networks is 84kb and includes 2685 channels, includes country specific and even local tv channels.

We'd then need to do a API request with the channel id to get the logo URL:
https://developers.themoviedb.org/3/networks/get-network-images

Example of a reply from the API:
```JSON
{
  "id": 3308,
  "logos": [
    {
      "aspect_ratio": 2.425287356321839,
      "file_path": "/tuomPhY2UtuPTqqFnKMVHvSb724.png",
      "height": 174,
      "id": "5d6bb5e15f2db100105137e7",
      "file_type": ".svg",
      "vote_average": 0,
      "vote_count": 0,
      "width": 422
    }
  ]
}
```

We can then use `file_path` to get the logo URL, in various forms:
- white no background: https://image.tmdb.org/t/p/h100_filter(negate,000,666)/tuomPhY2UtuPTqqFnKMVHvSb724.png
- standard: https://image.tmdb.org/t/p/h100/tuomPhY2UtuPTqqFnKMVHvSb724.png

This would be a pretty cool feature, but the issues I see with it is the fact that we'd need to search through 2500+ channel names to get a match.. we could although create a list with previously matched channels to not repeat old searches..

Pinging @Screwdgeh too as he might also be interested in this.

**Comment by jaruba** [comment]
There is no list that I know of for Tizen TV app logos, but that problem is much simpler then the tv channels one. We could just go through these 2 lists of most popular Tizen TV apps:
- https://tekdeeps.com/the-best-apps-for-your-samsung-smart-tv-with-tizen/
- http://vixi.tv/the-50-best-samsung-smart-tv-apps-list-2019/

and hardcode the app names + logos as a start, and leave it as a community effort to improve on the app list.

**Comment by Screwdgeh** [comment]
This is indeed very sexy. Just checked it out for Spotify media player and looks sexy as hell!

I have been looking more into this and found various options, none of them ideal though:
- TMDB - has a good list of networks, no API call to search for a network (so would have to go off of downloading latest list and then matching ourselves) - the website has a call that returns the networks for a query (https://www.themoviedb.org/search/network?query=eurosport), but unfortunately then in the results list the name is not mentioned again, so further queries would be required to fetch the name based on network id and then do further matching in case of multiple results... So best would be to download latest network list at component initialization and match against that and only fetch and cache images when needed upon a title match - not ideal though! We may choose as part of update to fetch a new list every so often, e.g. once every week. With 84 kB that seems fair enough? I'll contact them to see if we overlooked anything...
- Maze - has a good list of networks (https://www.tvmaze.com/networks), but also has no API call to query networks list... similar problem as above - I'll contact them to see if there is maybe something undocumented we could use.
- TVDB/TVRage - only outdated list of networks and typically without logos, no go.
- Website lyngsat-logo.com - also very extensive list of networks, but no API and copyright protected...

I wonder even if this should be a seperate metadata agent component that would contribute improved media metadata including entity picture support across any media player but not yet sure how that could work (as I believe a component cannot override another components state attributes... adding more state attributes would work though, but ideally it would also improve e.g. the media title). Could even rely on code from Plex/Kodi who do this really well. Anyway... that's too big a scope for how much I'm willing to invest... so no sense in daydreaming...

Let's wait for responses and see... otherwise happy to try along the TMDB route as the most viable.

**Comment by jaruba** [comment]
@Screwdgeh oh, you researched quite a lot, I just made a 40 line app to scrape all images from TMDB (took about 10-15min), it resulted into this file which I uploaded to the repo:
https://github.com/jaruba/ha-samsungtv-tizen/commit/e33c183bae306b8ae83d4212d4e070c263aa3368

There are 1555 TV networks in there with their logo paths from TMDB, the file size is 74kb, I set the property names (tv network names) to lowercase for easier matching. Also TMDB considers "Netflix", "Disney+", "Rakuten TV", etc to be TV networks for some reason, but this is in our advantage as we can now match TV apps from the same file too.

It should be as easy as just reading the JSON file in python and `logo_paths[self._source.lower()]` and using the TMDB prefixes for images:
- white no background: https://image.tmdb.org/t/p/h100_filter(negate,000,666)/tuomPhY2UtuPTqqFnKMVHvSb724.png
- standard: https://image.tmdb.org/t/p/h100/tuomPhY2UtuPTqqFnKMVHvSb724.png

Not sure when I'll find more time to try it out, you can try implementing it if you want.

**Comment by Screwdgeh** [comment]
First small tryout with entity picture with URLs from the list... Home Assistant is kind of retarded (or probably I am) - it clearly takes the prevalent color out of the picture and uses that as background color... with a transparent picture and only the logo color the end result is that the background color is always the same as the logo (hence logo not visible). 

So we need logo's actually with a well chosen background color! 

And another issue is aspect ratio. It supports square images really well, rectangular images partly disappear. So we need to append to image size to match a square ratio as well if we want the entire logo visible.

This:
![image](https://user-images.githubusercontent.com/58153180/96791859-85f2d300-13f9-11eb-957a-624d9ac6efea.png)

Becomes:
![image](https://user-images.githubusercontent.com/58153180/96791481-d9185600-13f8-11eb-9ba7-d8eaf6181622.png)

Will need to fiddle around later...

**Comment by jaruba** [comment]
@Screwdgeh I could make a bot that processes all the pictures.. so it makes them all square and of the same size, sets a background color and a padding.. then put them up somewhere..

**Comment by jaruba** [comment]
@Screwdgeh I left the bot running last night and made 2 new prefixes that we can use (instead of the TMDB ones).

- colored logo, white background: `https://jaruba.github.io/channel-logos/fff`
- white logo, dark background: `https://jaruba.github.io/channel-logos/212c39`

Can you try them out? I left the exact same image filenames as in `logo_paths.json`, so it should be a drop-in change by just replacing the TMDB image prefixes with the new ones.

**Comment by Screwdgeh** [comment]
Wow, you're quick with this stuff, impressive 😊! This is certainly much better! Some examples:

White background:
![image](https://user-images.githubusercontent.com/58153180/96933550-f0bb1180-14c0-11eb-9c65-9effdb0be764.png)
![image](https://user-images.githubusercontent.com/58153180/96933799-6cb55980-14c1-11eb-9925-70bb05a4abc6.png)
![image](https://user-images.githubusercontent.com/58153180/96933938-ab4b1400-14c1-11eb-9b20-9ca093c7f65f.png)
![image](https://user-images.githubusercontent.com/58153180/96934153-0a108d80-14c2-11eb-9bac-ebc58dcbe114.png)

I love that the color helps view at a glance which channel you are likely at due to the whole entity changing color. But it does look pretty poor when the logo is just 1 color... which I'm afraid most of them actually are...

Dark background:
![image](https://user-images.githubusercontent.com/58153180/96934451-7e4b3100-14c2-11eb-8572-9159697bbcdf.png)
![image](https://user-images.githubusercontent.com/58153180/96934486-902cd400-14c2-11eb-9508-b379f277c6c0.png)
![image](https://user-images.githubusercontent.com/58153180/96934548-adfa3900-14c2-11eb-8d36-b5b3a5e418d0.png)
![image](https://user-images.githubusercontent.com/58153180/96934590-c10d0900-14c2-11eb-9bec-459547e41a2a.png)

The dark looks more calm and streamlined, but does make it harder to see at a glance what is playing.

**Comment by jaruba** [comment]
I think we should make a setting called `dark_theme` which is `False` by default. And use the dark version if this is set to`True`. I think the dark ones are clearly not as nice, but there is a need for this for users that use dark lovelace themes.

Can u add the setting too? Otherwise just commit what u have and I can add the setting, ur choice.

**Comment by jaruba** [comment]
@Screwdgeh Any reason why you haven't committed yet? If you got stuck with something tell me how I can help.

**Comment by Screwdgeh** [comment]
Hey @jaruba... sorry had some private things to take care of... I made a commit with the changes. To test it add show_logos: "dark" or show_logos: "color" to the component config.

It looks very good and the image matching is working very well for me! 

Some edge cases not covered yet for own channel names, like e.g. combined channel names I get returned for some channels, such as "Veronica HD / Disney XD".

How do you feel about making this long term? Things like:
- Fetching images directly from TMDB API/file download and manipulating them on the fly?
- Adding possibility to override logos by adding images to a local HA folder 'logos\<network name>.png'
- Let me also know performance on your end - right now it's a synchronous function, but performance looks absolutely fine on my end (<1s to match a logo). Ideally we move the logo matching to an async function in line with guidelines.

**Comment by Screwdgeh** [comment]
By the way, was your intention to do this on the 'source-logos' branch? I updated to master because I saw your logo_paths json file there too... Only later noticed the branch.

**Comment by jaruba** [comment]
Sorry for insisting, I'm just excited about this feature. I made the other branch to commit the `logo_paths.json` to it, as I wasn't sure we'll be able to integrate it at first, but I pushed that file through the GH web UI to the master branch by mistake. Now that we know it's doable though, there's no problem to use the master branch for this.

Manipulating the images on-the-fly could be troublesome, we'd either need to start a web server in the addon to export them or pay for a server that will manipulate them for all users. I think the way we do it right now is the most efficient way, and I can update the list and logos in minutes by just running the bot again. When it comes to streaming services and tv channels, it's a rare event for a new one to appear, so updating the list isn't something that needs to be done frequently.

Regarding custom logos, we can (even now) change the logo or add new channel paths by editing `logo_paths.json` (the bot won't overwrite previous changes to this file, it will only add new entries if available), and adding a new logo to the `channel-logos` repo I made on GH. I wouldn't give users the possibility of adding logos locally to their setup because I prefer incentivizing the users to collaborate on the component so it leads to better UX for everyone.

Regarding sync vs async, I'll test and give u my results, it's possible that HA gives some warning if we use sync though. (It usually does)

**Comment by jaruba** [comment]
There is, although, one flaw with pre-processing images like we currently do. It doesn't handle rebranding, if a logo changes it can't account for that change, because it only adds new entries. I can make it redo all images every time, but then if we manually edit a logo, that change will be overwritten, we can although add logos for channels that are not on the list, and that change will be persisted until TMDB adds that channel also.

I'll leave it like this for now, and if I see that nobody is interested in changing the TMDB logos, I'll make it handle the rebranding scenario too.

**Comment by jaruba** [comment]
Btw, u should be aware that I'm going to change the default port ( https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L65 ) to `8002` in the next release. Both my 2017 TV and 2019 TV use `8002`, the `8001` port hasn't been used for too many years already. Just telling you in case some users will complain about the component breaking for them after this change, in which case they should set the port to `8001` in their config.

**Comment by zappasmart** [comment]
Guys, great job!
I have a small comment so far.

For the background, I think we should allow using the primary color of the home assistant theme currently selected, as an alternative to the automatic color.

This will be more consistent with how the media player card looks by default when TV is on:
![image](https://user-images.githubusercontent.com/53600373/97162549-a61aed00-177f-11eb-8b73-d2f0d33be4be.png)

A dark background might not visually inform the TV is on.

**Comment by jaruba** [comment]
@zappasmart I can make a version of the logos with blue background, but the logos themselves will need to be white (like in the dark examples) because otherwise we can't ensure that HA will use the blue color for the card background, it seems to use the primary color of the image and there's no setting to change that.

**Comment by zappasmart** [comment]
If I try to set a white image with transparent background like this one:
https://www.iconsdb.com/icons/preview/white/chat-4-xxl.png

I get this correctly:
![image](https://user-images.githubusercontent.com/53600373/97171399-ae7a2480-178d-11eb-8f57-d6e763e0bb2c.png)

The Media Control Card uses the theme's primary color for the background.

But if I use this from TMDB:
https://image.tmdb.org/t/p/h100_filter(negate,000,666)/tuomPhY2UtuPTqqFnKMVHvSb724.png

I get this (no picture displayed):
![image](https://user-images.githubusercontent.com/53600373/97171576-fbf69180-178d-11eb-89f6-a55162fd8b71.png)

Any idea?

**Comment by zappasmart** [comment]
@jaruba regarding your image processing POC, can you try to generate white images on a transparent background?
I'd like to test how they are digested by the Media Control Card.

**Comment by Screwdgeh** [comment]
From my experience pure white images with a transparent background will work to keep the theme's primary color. Pure white is always ignored in selecting a background color. If it can't find any it will stick to theme's primary color. All other colors are picked up as a selection for component background color.

@zappasmart not sure what is wrong with the PNG as https://image.tmdb.org/t/p/h100_filter(negate,000,666)/tuomPhY2UtuPTqqFnKMVHvSb724.png -> I get the same effect, but downloading and saving to local hass folder and showing from there it works fine. 

The greyscale as currently produced in some logos will not work the same and the gray will be picked up as background color. Maybe I'm too pessimistic, but sadly I think automatically converting the color logos to pure white will screw up some logos and will make them unreadable or make them unrecognizable (see examples above). I'll leave to @jaruba for further comment if he thinks differently...

**Comment by Screwdgeh** [comment]
> Sorry for insisting, I'm just excited about this feature. I made the other branch to commit the `logo_paths.json` to it, as I wasn't sure we'll be able to integrate it at first, but I pushed that file through the GH web UI to the master branch by mistake. Now that we know it's doable though, there's no problem to use the master branch for this.

OK

> Manipulating the images on-the-fly could be troublesome, we'd either need to start a web server in the addon to export them or pay for a server that will manipulate them for all users. I think the way we do it right now is the most efficient way, and I can update the list and logos in minutes by just running the bot again. When it comes to streaming services and tv channels, it's a rare event for a new one to appear, so updating the list isn't something that needs to be done frequently.

True, it's not that frequent... but I'm mostly not in favor of manual work. Hass does have the built-in web server (additional files located in 'www' folder are automatically hosted), couldn't we use that? I guess it depends on how much processing power is required for the conversion process and whether it can all be done in Python.

> Regarding custom logos, we can (even now) change the logo or add new channel paths by editing `logo_paths.json` (the bot won't overwrite previous changes to this file, it will only add new entries if available), and adding a new logo to the `channel-logos` repo I made on GH. I wouldn't give users the possibility of adding logos locally to their setup because I prefer incentivizing the users to collaborate on the component so it leads to better UX for everyone.

Fully recognize that we should be able to benefit of each other's work! So agreed that repository contributions could be the way to go. I was checking and TMDB only accepts networks that are 'original content creators', so many tv channels we are interested in would not be accepted by them. Furthermore there is no automated entries for networks and it would have to be done as a forum post.

> Regarding sync vs async, I'll test and give u my results, it's possible that HA gives some warning if we use sync though. (It usually does)

I'll make it work in async to be safe. I'll have a look at that later today, I think it's quite easy to achieve, just need to test if everything works fine still.

**Comment by jaruba** [comment]
@zappasmart @Screwdgeh 

So here's what I did, I changed the paths to the previous images (made a commit to use the new paths), and added 4 more image prefixes.

Currently we have:

- white background, colored logo: `https://jaruba.github.io/channel-logos/export/fff-color`
- dark background, white logo: `https://jaruba.github.io/channel-logos/export/212c39-white`
- transparent background, colored logo: `https://jaruba.github.io/channel-logos/export/transparent-color`
- transparent background, white logo: `https://jaruba.github.io/channel-logos/export/transparent-white`
- blue background, colored logo: `https://jaruba.github.io/channel-logos/export/05a9f4-color`
- blue background, white logo: `https://jaruba.github.io/channel-logos/export/05a9f4-white`

I also open sourced the bot, it's available on NPM: https://www.npmjs.com/package/channel-logos

Anyone can use it now to update `logo_paths.json` and/or create new logo versions based on their own preferences.

@Screwdgeh 

> Hass does have the built-in web server (additional files located in 'www' folder are automatically hosted), couldn't we use that?

I'm not sure we can, we might not have access to write to that file. Addons are normally sandboxed to prevent them from breaking things. With this said, I haven't tried though..

> I guess it depends on how much processing power is required for the conversion process and whether it can all be done in Python.

I used Node.js for the bot as it's the primary programming language I work with, so I work the fastest with it.

> I was checking and TMDB only accepts networks that are 'original content creators', so many tv channels we are interested in would not be accepted by them.

This might not be as limited as you think.. Keep in mind that "original content creators" also means creators of Talk Shows, Game Shows, News Shows, Reality Shows, Sports, etc. etc. All channels that I know of have some original content..

**Comment by jaruba** [comment]
We can now set `show_logos` to any of these values: 'blue-color', 'blue-white', 'dark-white', 'white-color', 'transparent-color', 'transparent-white'. Default is 'white-color'.

**Comment by jaruba** [comment]
@zappasmart @Screwdgeh

Please test it when u have some time, if everything goes well I'd release an initial version with this feature. If we find better ways to do this we can change it in the future.

**Comment by Screwdgeh** [comment]
Let me try and get a bunch of logo updates for Dutch television (a few missing and a few outdated logos) to TMDB and see how far I get, confidence level not very high.

The new color options are also sexy! The blue-color combo actually works very well too, I'm not sure which one to pick now! I think I still like the 'white-color' the best.

The transparent option sadly does not work very well as explained earlier (nor for color as the logo becomes invisible against the background, nor for white as most of them are grayscale rather than true white, making again at least parts of the logo blend against the background color).

Made 2 commits with some small changes: 
- option for 'none' to disable logos completely (documentation update included)
- run the media update (title and image) as an async job instead which should prevent the warnings the update takes long. This way it does take a bit longer when a new logo needs to be looked up, but it still updates the title and picture at the same time so impact is minimal I'd say.

Good to go from my point of view!

**Comment by zappasmart** [comment]
A few comments from my side:

- I'd change URL `fff-color` to `white-color` for naming consistency with the other options
- The `05a9f4 `options work well only if the user has the default theme. I don't use the default theme, I installed a theme I like more, so using those options will look visually inconsistent because of different blue colors
- for the same reason, do you think option `212c39` should be changed to a dark neutral color instead of dark blue?
- do you think it could be worth testing with other media player cards like the Mini Media Player? https://github.com/kalkih/mini-media-player

**Comment by jaruba** [comment]
@zappasmart 

- the URL patterns are generated from the HEX color code and logo preference, i'd rather not change this, the setting in the config is `white-color` for it though
- the `blue` option is obviously for a specific case, but many may use the default theme so there may be a purpose for it, as the transparent ones aren't working as one would expect
- i've changed the color of `dark-white` to a neutral color, and renamed the previous one to `darkblue-white`
- i'm not sure what you're asking regarding Mini Media Player, i never used it

**Comment by jaruba** [comment]
I released v1.5.4

**Comment by zappasmart** [comment]
I've tested a bit with the Italian TV channels and looks good so far. Thank you for your efforts in implementing it!

**Comment by Screwdgeh** [comment]
Further update on my efforts at TMDB. Seems I was sorely mistaken on ways to edit the database! The good news is that anyone is able to edit existing networks including logos via TMDB UI and also add any that are missing. Although not super straight forward it is definitely possible! I added documentation to the component on how the information can be updated.

Since this can really be done properly and it also helps TMDB to have an updated list of TV networks, my suggestion/request is that we also proactively pick up **any changes** we get from TMDB. This also makes me wonder - I saw networks with multiple logos... do you know what logic you use to pick one? Just the first or last or?

Next to TMDB we should have a separate source of app icons. I went through the list of most popular Samsung Smart TV apps and though of some popular other sources used (Chromecast, Xbox, Playstation, Nvidia SHIELD, Nintendo switch, Wii). Have a set of 40 logos ready. But I see we have no way of adding logos for these yet. Propose we make an 'app_logo_import' folder in the repository or create a seperate repository for app logos? What do you think @jaruba?

I've started looking into the component and given I have a bit of NodeJS experience as well, happy to start contributing there too.

**Comment by jaruba** [comment]
@Screwdgeh 

> my suggestion/request is that we also proactively pick up any changes we get from TMDB

Sure, we can make such a change easily, but it will take significantly more time to update. I can improve on the logic a lot though, I can add a folder to download both versions of the logo first, add the folder to `.gitignore`, then start processing all the versions we're using from the local files. If I want to go full psycho on it, I could check the headers before downloading the logos, if the `content-length` didn't change, it won't update it at all. 😛 

> This also makes me wonder - I saw networks with multiple logos... do you know what logic you use to pick one? Just the first or last or?

I just use the first in the logo array: https://github.com/jaruba/channel-logos/blob/main/pull.js#L50

> I went through the list of most popular Samsung Smart TV apps and though of some popular other sources used (Chromecast, Xbox, Playstation, Nvidia SHIELD, Nintendo switch, Wii).

If we add Nvidia Shield, we'd better add other popular smart boxes too: Fire TV, Fire Stick, Apple TV, etc.

> But I see we have no way of adding logos for these yet.

There is no reason to not use the `channel-logos` repo for extra logos too, as those are not just channel logos anyway, TMDB includes: Netflix, Disney+, etc. also.

My thinking is this:
- we can edit the `logo_paths.json` from the `channel-logos` repo directly, when you pull a new version of the file it will not remove the non-TMDB entries from the file
- add a `other` folder in the root of the `web` branch, we can also make 2 folders in `other`, a `color` folder and a `white` folder, and put the logos there accordingly, if we have only color versions that should not be an issue, the logic will just fail for all "white" versions of that logo and it shouldn't show in HA

Let's presume a new entry is `"xbox": "/xbox.png"`, it will first try to get `/xbox.png` from the `./other/color/` folder, if it fails, then it tries to get it from TMDB.

> I've started looking into the component and given I have a bit of NodeJS experience as well, happy to start contributing there too.

I added you as a contributor to `channel_logos`.

You'll probably notice the funny way I used to edit the images. I use `puppeteer` which in turn uses Chrome. I'm creating a 200x200 headless browser window and use CSS for styling the page, then I take a screenshot of that browser window, that's our new image. 😅

**Comment by jaruba** [comment]
@Screwdgeh I updated the `channel-logos` repo to support custom images. Just upload them to this folder: https://github.com/jaruba/channel-logos/tree/main/custom

You only need to add the colored versions of the logos, as it can make the white versions from them itself now.

There is a readme in that folder explaining how it should be used. Ping me once it's done so I can update all the logo images again.

**Comment by Screwdgeh** [comment]
Hey @jaruba - great!

I did not have write access to the repository, so created a fork and pull request for now: https://github.com/jaruba/channel-logos/pull/1

Have a look through the logos and let me know if we have missed any crucial ones...

I have 1 other request - I have submitted several logo changes and (additions) at TMDB. Is it possible to implement update scenario for TMDB as well? At the same time I figured out that it would be best to: - take highest vote logo from the multiple logos presented by TMDB - if multiple logos have the highest vote, take the last from the array as it seems the last in the array is the one actually added last, so most recent. It seems TMDB applies the same logic to show network logo on their website.

Would be great to see them show up after your update!

**Comment by jaruba** [comment]
@Screwdgeh 

So I redid all the images, I didn't add the logic you proposed yet though (but the logic seems fair so I'll look into adding it), you can test the `master` branch of this repo if you want, I'll hold back on making a new release for the moment. There seems to be an issue in `puppeteer` where the _screenshots_ I make are of a poor quality. All tickets regarding this seem to suggest using `deviceScaleFactor: 2` which makes our 200x200 images become 400x400. (same as just making them 400x400 in the first place tbh, should probably look into using `deviceScaleFactor: 1.5`)

This makes the images be of a better quality because it literally resizes them in the browser for our needs, but it also makes what was previously a 14kb image be a 45kb image..

Let's see how it goes..

Another thing to note is that instead of hardcoding `logo_paths.json`, we could download it from `https://jaruba.github.io/channel-logos/logo_paths.json`, which would make the HA component update in real time instead of updating whenever we update the component.. But it's a 74kb file, which would need to be downloaded every time HA restarts.. Not sure what would be best in this case.. (given that a single image is 45kb in the current case..)

Opinions on all this are welcomed.

Future planned tasks regarding this:
- use @Screwdgeh 's logo choosing logic
- download all images first to a `/temp` folder before reprocessing all the images (would increase speed a lot)
- check the `content-length` header of TMDB remote images before downloading to ensure that we're not redownloading the same images (would increase speed a lot)
- run the bot on an interval
- bot should auto-update the github repository periodically

**Comment by Screwdgeh** [comment]
Sounds great @jaruba! I can make the changes to download the logo_paths.json periodically. We can just write to file and check modification date of the file every so often to see if it requires updating, that would avoid downloading every time at an HA restart. Need to check if we can do same thing using content-length to avoid downloading the file if it is the same.

**Comment by Screwdgeh** [comment]
@jaruba I have added the functionality as described above. It even checks the file modification date online via http header (HTTP HEAD to only fetch the headers) first and only downloads it if that is more recent than the file stored locally. You could use this same mechanism for the images from TMDB API if it provides the same functionality of the 'Last-Modified' header in the header response.

I did run into 1 issue for my own installation: I copied the original component over with a non-hass user account, meaning the hass account running home assistant did not automatically have write access to the paths file to edit it and resulted in a permissions issue. If we want to be safe it is best to leave the logo_paths.json out and download it first time the component starts. Then there should not be any permission issues. Do you agree to remove the logo_paths.json file from the files to prevent this issue from happening?

Out of interest - did you update the logo_paths file with new TV channels from TMDB or not yet? Because I did not see the logos appearing yet for the new TV channels I added there (e.g. 'Ziggo Sport' and 'RTL Z')... If you do update it let me know, immediately a good test!

**Comment by jaruba** [comment]
@Screwdgeh 

> You could use this same mechanism for the images from TMDB API if it provides the same functionality of the 'Last-Modified' header in the header response.

I was actually overthinking this, I can just check against the filenames to know if it's the same image or not.. lol..

> I did run into 1 issue for my own installation: I copied the original component over with a non-hass user account, meaning the hass account running home assistant did not automatically have write access to the paths file to edit it and resulted in a permissions issue.

I was actually thinking that it might be a good idea to still leave the `logo_paths.json` in the component (and rename it to `logo_paths_local.json`), we could then use it as a backup if there's any error (whatsoever) during downloading / writing the remote file. The one in the component would just update when we update the component.

The thing is that there are many issues that can arise from attempting to download / write the file.. we should not fully rely on downloading for this feature.

> Out of interest - did you update the logo_paths file

I don't think I updated the `logo_paths` file, only the images. I'll do another update as soon as I change the logic as different logos will be chosen.

**Comment by Screwdgeh** [comment]
> I was actually overthinking this, I can just check against the filenames to know if it's the same image or not.. lol..
> 
> >

I guess indeed you can't edit existing images on TMDB, so they will always get a new URL indeed lol

> I was actually thinking that it might be a good idea to still leave the `logo_paths.json` in the component (and rename it to `logo_paths_local.json`), we could then use it as a workaround if there's any error (whatsoever) during downloading / writing the remote file. The one in the component would just update when we update the component.
> 
> The thing is that there are many issues that can arise from attempting to download / write the file.. we should not fully rely on downloading for this feature.

Done in a new commit. Small change, guess you're right this is safest and given the logo_paths don't update often this still has value to the user! We can keep `logo_paths.json` as is... I download a new file under `logo_paths_download.json` and keep it as recent as possible checking against the online repository.


> I don't think I updated the `logo_paths` file, only the images. I'll do another update as soon as I change the logic as different logos will be chosen.

Clear - let me know when you do - curious to see the autoupdate do its magic!

**Comment by jaruba** [comment]
@Screwdgeh 

I updated `logo_paths.json` in `channel-logos`, and also updated all the logos based on your proposed logic (top score first, alternatively the last logo in the array)

Test it out.

If everything works correctly, all that's left is to make a script to run the bot monthly.

**Comment by Screwdgeh** [comment]
Works as expected while testing today, updated file was downloaded automatically and I can see all the added and updated logos while browsing through the related tv channels!

Awesome stuff!
