### ISSUE TITLE
out of sync error

### ISSUE THREAD

**Issue by leonardpitzu** [jaruba/ha-samsungtv-tizen#49]
i keep seeing in logs the error

`media_player.ourtv: Sources out of sync. Restart Home Assistant`

the tv is controllable as expected but every now and then it does not know the state of the tv (i.e. it thinks the tv is off when it is on or vice versa).
tv is controlled locally from a docker container.

**Comment by jaruba** [comment]
That warning should be related to the source list (example: TV, HDMI1, etc.) that you use to change the source on your TV. I've never seen it before though.

As for your on / off states, you can try to change the `update_method` to a different one, see what fits your situation more.

**Comment by leonardpitzu** [comment]
`update_method` is `ping`
as for the error - i see it all the time, not only when i change the `input`  source, which looks like this
`source_list: '{"TV": "KEY_TV", "AppleTV": "KEY_HDMI"}'
  app_list: '{"Netflix": "11101200001", "YouTube": "111299001912"}'`

**Comment by jaruba** [comment]
It's possible that u get the warning because the active source is unknown, and the source can't be known because there is no way to get it from the local APIs of Samsung TVs. If u enable the SmartThings API and use the `ST_` keys u will get the correct active source.

As for the `update_method`, as I already said, try different options, see if u like them or not, the smartthings one will obviously only work if u enabled the SmartThings API.

**Comment by leonardpitzu** [comment]
Works great using SmartThings.
Thanks!

**Comment by jaruba** [comment]
Happy to hear it, hope it works well for u in the future too. Using the remote API isn't an actual security issue, this data is sent to the SmartThings servers regardless if u use it or not. (as it is needed for the SmartThings app, if u ever choose to use it or not)

It's better to enable it in the component, as at least this way u use it to further extend the features of this component as well. If u still have issues with the update method, u can still try playing around with the available options, they will act a bit differently due to the SmartThings API being enabled, as the component has more data to crunch this way.

I will close this ticket, if u still have issues u can reopen it or open another one.
