### ISSUE TITLE
Should the integration be reporting the media state?

### ISSUE THREAD

**Issue by sirs2k** [jaruba/ha-samsungtv-tizen#55]
Sorry if I've missed this detail.

I've managed to get this working with my NU8000, but the media_player does not report when media is playing or idle...

Am I missing something?

**Comment by jaruba** [comment]
it's not supposed to report the media state, as it cannot know it. there are too many various scenarios: tv channels, apps, casting, external devices,

**Comment by jaruba** [comment]
i am although looking into making a general pause/play button that takes into account the media source, but more then that... i simply don't think it's possible to generalise the media state, nor have enough data to crunch for something like that

**Comment by sirs2k** [comment]
I'm confused as my Bravia TV integration does exactly that....

When it's playing netflix or plex it shows as playing, when not it shows as idle

I've managed to get the state when plex is playing by adding the plex integration.
Can you think of a way that can see when netflix is playing?

**Comment by jaruba** [comment]
Why do people compare Sony with Samsung? There are obvious differences:
- vendor
- PRICE
- operating system
- quality of development
- overall quality of product

Do I really need to address your surprise that ur new Samsung TV can't do what ur Bravia TV does? 

I am not a fan of being cornered in by limits of ur own buying choices. It is what it is.

This is an open source repository, and it handles things better then any other out there atm. This is because i put a lot of time and effort into it.

So there are 2 ways of going about this:
- accept when i tell u something as i'm dedicating my time to helping u and reducing ur confusion from all the knowledge i gathered until now
- contribute by finding something that i may have missed, implement it and create a pull request
- contribute by donating which allows me to dedicate a bit more time to finding the things i may have missed before

What u shouldn't do:
- whine by saying that Sony is better

**Comment by sirs2k** [comment]
lol I was not expecting that reply. Very disappointing

I was not `whining` as you put it so bluntly. I was simply trying to educate you on what I meant as it seemed you had no clue what I was talking about...

> it's not supposed to report the media state, as it cannot know it. there are too many various scenarios: tv channels, apps, casting, external devices, etc

It's interesting how you compare Sony as the leading manufacturer and that I chose Samsung as it was a poor choice due to budget and what not, it's in fact the exact opposite 

> This is an open source repository, and it handles things better then any other out there atm. This is because i put a lot of time and effort into it.

Pfttt, please get over yourself... Since you mentioned it, in the past hour I thought I'd give this integration a try https://github.com/ollo69/ha-samsungtv-smart and its giving me more control and it's snappier 

While I appreciate all the work you have put in, your attitude sucks balls!
Go get laid or smoke a joint or whatever you need to do, although I doubt anything would work...

**Comment by jaruba** [comment]
I gave u my answer and u failed to accept it, u then continued by comparing products from different vendors. Do you know what self-entitlement is? Nowhere in ur text did i feel any appreciation, u just wanted something for nothing and were prepared to push for it.
